module ITC99

//                ["STATO_REG_1_";
//                "STATO_REG_0_"]
//                  ["STATO_REG_0_";
//                    "CODA0_REG_2_";
//                    "CODA0_REG_1_";
//                    "CODA0_REG_0_";
//                    "CODA1_REG_2_";
//                    "CODA1_REG_1_";
//                    "CODA1_REG_0_";
//                    "CODA2_REG_2_";
//                    "CODA2_REG_1_";
//                    "CODA2_REG_0_";
//                    "CODA3_REG_2_";
//                    "CODA3_REG_1_";
//                    "CODA3_REG_0_";
//                    "GRANT_REG_3_";
//                    "GRANT_REG_2_";
//                    "GRANT_REG_1_";
//                    "GRANT_REG_0_"]

//                    ["D_OUT_REG_7_";
//                    "D_OUT_REG_6_";
//                    "D_OUT_REG_5_";
//                    "D_OUT_REG_4_";
//                    "D_OUT_REG_3_";
//                    "D_OUT_REG_2_";
//                    "D_OUT_REG_1_";
//                    "D_OUT_REG_0_";
//                    "OLD_REG_7_";
//                    "OLD_REG_6_";
//                    "OLD_REG_5_";
//                    "OLD_REG_4_";
//                    "OLD_REG_3_";
//                    "OLD_REG_2_";
//                    "OLD_REG_1_";
//                    "OLD_REG_0_"; 
//                    "STATO_REG_1_";
//                    "STATO_REG_0_";
//                       "D_IN_REG_0_";
//                       "Y_REG"]
